Repository alkem-io/client-web, pull requests merged in 2024-12, with the labels that each got.

#7271 remove community guidelines content functionality
  src/core/apollo/generated/apollo-helpers.ts
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/core/i18n/en/translation.en.json
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/domain/community/community/CommunityGuidelines/CommunityGuidelines.graphql
  src/domain/community/community/CommunityGuidelines/CommunityGuidelinesBlock.tsx
  src/domain/community/community/CommunityGuidelines/CommunityGuidelinesContainer.tsx
  src/domain/community/community/CommunityGuidelines/CommunityGuidelinesForm.tsx
  src/domain/journey/space/pages/AdminSpaceCommunityPage.tsx
Labels: bug squash, enhancement, UX

#7284 Add delete functionality for community guidelines
  src/core/i18n/en/translation.en.json
  src/domain/community/community/CommunityGuidelines/CommunityGuidelinesContainer.tsx
  src/domain/community/community/CommunityGuidelines/CommunityGuidelinesForm.tsx
  src/domain/journey/space/pages/AdminSpaceCommunityPage.tsx
  src/domain/journey/subspace/pages/AdminSubspaceCommunityPage.tsx
Labels: client, UX

#7307 add new alkemio banner
  public/alkemio-banner/global-banner.jpg
  public/alkemio-banner/global-banner.svg
  src/domain/common/profile/ProfilePageBanner.tsx
  src/main/ui/layout/topLevelPageLayout/TopLevelPageBanner.tsx
Labels: client, enhancement

#7300 Client web/6607 embed code in post (iframe)
  src/core/i18n/en/translation.en.json
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
  src/core/ui/forms/MarkdownInputControls/InsertEmbedCodeButton/Iframe.ts
  src/core/ui/forms/MarkdownInputControls/InsertEmbedCodeButton/InsertEmbedCodeButton.tsx
  src/core/ui/forms/MarkdownInputControls/InsertImageButton.tsx
  src/core/ui/forms/MarkdownInputControls/MarkdownInputControls.tsx
  src/core/ui/markdown/WrapperMarkdown.tsx
  src/core/ui/markdown/embed/allowedEmbedUrls.ts
  src/core/ui/markdown/embed/remarkVerifyIframe.ts
  src/core/ui/markdown/html/UnifiedConverter.ts
  src/domain/collaboration/callout/creationDialog/CalloutCreationDialog.tsx
Labels: client

#7306 VC Add/Invite Functionality and UI from the Space -> Community
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/core/i18n/en/translation.en.json
  src/domain/community/community/CommunityAdmin/useCommunityAdmin.ts
  src/domain/community/community/VirtualContributorsBlock/VirtualContributorsBlock.tsx
  src/domain/community/community/useCommunityAssignment/VirtualContributors.graphql
  src/domain/community/inviteContributors/InviteContributorsDialog.tsx
  src/domain/community/inviteContributors/InviteContributorsList.tsx
  src/domain/community/inviteContributors/InviteContributorsProps.tsx
  src/domain/community/inviteContributors/InviteVCsDialog.tsx
  src/domain/community/inviteContributors/PreviewContributorDialog.tsx
  src/domain/community/inviteContributors/VirtualContributors.graphql
  src/domain/community/inviteContributors/useInviteContributors.tsx
  src/domain/community/user/userCard/UserCard.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfileContentView.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfilePage.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfilePageView.tsx
  src/domain/community/virtualContributor/vcProfilePage/model.ts
  src/domain/journey/common/AboutPageContainer/AboutPageContainer.tsx
  src/domain/journey/space/SpaceCommunityPage/SpaceCommunityPage.tsx
  src/domain/journey/subspace/pages/SubspaceAboutPage.tsx
Labels: client

#7352 fix forum discussion styles
  src/domain/communication/discussion/views/DiscussionView.tsx
Labels: client
