Repository alkem-io/client-web, pull requests merged in 2024-11, with the labels that each got.

#7125 implement temporaryLocation flag logic
  .gitignore
  src/core/ui/forms/FormikFileInput/FormikFileInput.tsx
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
  src/core/ui/forms/MarkdownInputControls/InsertImageButton.tsx
  src/core/ui/forms/MarkdownInputControls/MarkdownInputControls.tsx
  src/core/ui/upload/FileUpload/FileUpload.tsx
  src/domain/collaboration/callout/CalloutForm.tsx
  src/domain/collaboration/callout/creationDialog/CalloutCreationDialog.tsx
  src/domain/journey/subspace/forms/CreateSubspaceForm.tsx
  src/domain/journey/subspace/subspaceHome/dialogs/SubspaceDialogs.tsx
  src/domain/platform/admin/components/Common/ReferenceSegment.tsx
  src/domain/storage/StorageBucket/useStorageConfig.tsx
  src/domain/templates/components/Dialogs/CreateEditTemplateDialog/CreateTemplateDialog.tsx
  src/domain/templates/components/Forms/CalloutTemplateForm.tsx
  src/domain/templates/components/Forms/CommunityGuidelinesTemplateForm.tsx
  src/domain/templates/components/Forms/PostTemplateForm.tsx
  src/domain/templates/components/Forms/TemplateForm.tsx
  src/domain/templates/components/TemplatesAdmin/TemplatesAdmin.tsx
  src/domain/timeline/calendar/CalendarDialog.tsx
  src/domain/timeline/calendar/views/CalendarEventForm.tsx
  src/domain/timeline/calendar/views/EventForm/EventForm.model.ts
  src/domain/timeline/calendar/views/EventForm/EventForm.tsx
Labels: client

#7157 [Simple Homepage] Redirect to space on Join clk + update the dash
  src/domain/community/invitations/InvitationActionsContainer.tsx
  src/domain/community/invitations/InvitationDialog.tsx
  src/domain/community/invitations/SingleInvitationFull.tsx
  src/main/topLevelPages/myDashboard/InvitationsBlock/InvitationsBlock.tsx
Labels: client

#7159 [Simple Homepage] UI changes to better support Mobile/Tablet Layout
  src/core/i18n/en/translation.en.json
  src/core/ui/content/PageContentBlockCollapsible.tsx
  src/main/topLevelPages/myDashboard/DashboardMenu/DashboardMenu.tsx
  src/main/topLevelPages/myDashboard/DashboardMenu/dashboardMenuTypes.ts
  src/main/topLevelPages/myDashboard/DashboardWithMemberships/DashboardActivity.tsx
  src/main/topLevelPages/myDashboard/MyDashboardWithMemberships.tsx
  src/main/topLevelPages/myDashboard/MyDashboardWithoutMemberships.tsx
Labels: client

#7171 Add privacy icon to space blocks
  src/core/i18n/ach/translation.ach.json
  src/core/i18n/bg/translation.bg.json
  src/core/i18n/de/translation.de.json
  src/core/i18n/en/translation.en.json
  src/core/i18n/es/translation.es.json
  src/core/i18n/fr/translation.fr.json
  src/core/i18n/nl/translation.nl.json
  src/core/i18n/pt/translation.pt.json
  src/core/i18n/ua/translation.ua.json
  src/domain/journey/common/JourneyCard/JourneyCard.tsx
  src/domain/journey/common/JourneyTile/JourneyTile.tsx
  src/domain/platform/admin/components/Group/GroupPage.tsx
  src/domain/platform/admin/components/Group/useDeleteUserGroup.ts
  src/main/topLevelPages/myDashboard/DashboardWithMemberships/DashboardSpaces/DashboardSpaces.tsx
  src/main/topLevelPages/myDashboard/ExploreSpaces/ExploreSpacesView.tsx
Labels: client

#7178 Аdd logic and update queries for privacy mode on journey
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/main/topLevelPages/myDashboard/DashboardWithMemberships/DashboardSpaces/DashboardSpaces.tsx
  src/main/topLevelPages/myDashboard/DashboardWithMemberships/DashboardWithMemberships.graphql
  src/main/topLevelPages/myDashboard/ExploreSpaces/ExploreSpacesView.tsx
  src/main/topLevelPages/myDashboard/recentSpaces/RecentJourneysList.tsx
  src/main/topLevelPages/myDashboard/recentSpaces/RecentSpaces.graphql
Labels: client

#7181 Memberships dialog not showing sumspaces data
  src/main/topLevelPages/myDashboard/myMemberships/ExpandableSpaceTree.tsx
  src/main/topLevelPages/myDashboard/myMemberships/MyMembershipsDialog.model.ts
Labels: bug, client

#7201 Hide pen button on closed link callout type
  src/domain/collaboration/callout/CalloutView/CalloutView.tsx
  src/domain/collaboration/callout/JourneyCalloutsTabView/CalloutsView.tsx
  src/domain/collaboration/callout/useCallouts/CalloutDetailsContainer.tsx
  src/domain/shared/components/References/ReferenceView.tsx
Labels: client, UX

#7198 Add loading indicators in innovation library
  src/core/ui/card/ContributeCardSkeleton.tsx
  src/domain/InnovationPack/CreateInnovationPackDialog/CreateInnovationPackDialog.tsx
  src/domain/InnovationPack/DashboardInnovationPacks/DashboardInnovationPacks.tsx
  src/domain/InnovationPack/DashboardInnovationPacks/InnovationPacksView.tsx
  src/domain/InnovationPack/DashboardLibraryTemplates/DashboardLibraryTemplates.tsx
  src/domain/InnovationPack/DashboardLibraryTemplates/LibraryTemplatesView.tsx
  src/main/topLevelPages/InnovationLibraryPage/InnovationLibraryPage.tsx
Labels: client, enhancement, UX

#7239 Show comments/contributors count only when there are any
  src/core/ui/typography/EllipsableWithCount.tsx
  src/domain/collaboration/InnovationFlow/InnovationFlowDialogs/InnovationFlowCollaborationToolsBlock.tsx
  src/domain/collaboration/callout/calloutBlock/sort/SortDialog.tsx
  src/domain/collaboration/callout/post/PostCard.tsx
Labels: enhancement, UX

#7251 Client web/7012 add search input in subspaces list view
  src/core/i18n/en/translation.en.json
  src/core/ui/list/LinksList.tsx
  src/domain/journey/common/JourneyFilter/JourneyFilter.tsx
  src/domain/journey/common/tabs/Subentities/ChildJourneyView.tsx
Labels: client, UX
