Repository alkem-io/client-web, pull requests merged in 2025-01, with the labels that each got.

#7399 Patch Release [v0.79.6]
  package-lock.json
  package.json
  src/core/ui/markdown/embed/allowedEmbedUrls.ts
Labels: bug, client

#7403 bump client version
  package-lock.json
  package.json
Labels: client

#7387 implement image pasting in md editor
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
Labels: client, feature

#7410 update contributors image for unauth user
  src/core/ui/content/PageContentBlockHeaderWithDialogAction.tsx
  src/domain/community/contributor/CommunityContributorsBlockWide/CommunityContributorsBlockWide.tsx
  src/domain/journey/space/SpaceCommunityPage/SpaceCommunityPage.tsx
  src/domain/journey/subspace/dialogs/ContributorsToggleDialog.tsx
Labels: client

#7415 bug fix: verified label overlaps with text
  src/domain/community/contributor/organization/OrganizationVerifiedStatus.tsx
  src/domain/community/profile/views/ProfileView/OrganizationProfileView.tsx
Labels: bug, client

#7404 add cspell config
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/core/i18n/en/translation.en.json
  src/core/ui/error/ErrorBlock.tsx
  src/domain/InnovationPack/InnovationPackProfilePage/InnovationPackProfilePage.tsx
  src/domain/collaboration/KnowledgeBase/KnowedgeBasePage.tsx
  src/domain/journey/common/tabs/Subentities/ChildJourneyCreate.tsx
  src/domain/journey/common/tabs/Subentities/ChildJourneyView.tsx
  src/domain/journey/subspace/subspaceHome/dialogs/SubspaceDialogs.tsx
  src/domain/platform/admin/components/Common/ReferenceSegment.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/ExternalAIComingSoonDialog.tsx
  src/main/ui/platformNavigation/PlatformNavigationUserMenu.tsx
Labels: client, enhancement, UX, DX

#7433 proper check for available account for the vc flow
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/useNewVirtualContributorWizard.tsx
Labels: client

#7428 Client web/7416 disable image pasting when hide image options flag is true
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
  src/domain/community/contributor/organization/OrganizationVerifiedStatus.tsx
Labels: client, enhancement, UX

#7439 Create Space Link - entitlements check added
  package-lock.json
  package.json
  src/main/topLevelPages/myDashboard/useCreateSpaceLink/useCreateSpaceLink.tsx
Labels: client

#7448 BUGFIX: Missing padding for the items on the left block on space and subspaces
  src/core/ui/list/LinksList.tsx
Labels: bug, client

#7463 restrict activities block to 10 results and add activities dialog
  src/main/topLevelPages/myDashboard/DashboardWithMemberships/DashboardActivity.tsx
  src/main/topLevelPages/myDashboard/latestContributions/LatestContributions.tsx
  src/main/topLevelPages/myDashboard/latestContributions/LatestContributionsProps.ts
  src/main/topLevelPages/myDashboard/latestContributions/myLatestContributions/MyLatestContributions.tsx
Labels: client

#7468 display usage-limit of spaces in the account page
  src/domain/community/contributor/Account/ContributorAccountView.tsx
Labels: bug, client

#7466 Fix add checkbox for tutorials UI bug
  src/domain/journey/space/createSpace/CreateSpaceDialog.tsx
Labels: bug, client

#7462 Bug fix: search bar in spaces page not working, and page refreshes on search term enter
  src/core/i18n/en/translation.en.json
  src/main/topLevelPages/topLevelSpaces/SpaceExplorerContainer.tsx
  src/main/topLevelPages/topLevelSpaces/SpaceExplorerPage.tsx
  src/main/topLevelPages/topLevelSpaces/SpaceExplorerView.tsx
Labels: bug, client, enhancement, UX

#7490 VC Flow - proper filtering of Existing Spaces
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/domain/community/contributor/Account/ContributorAccountView.tsx
  src/domain/journey/space/SpaceDashboard/SpaceDashboardView.tsx
  src/main/topLevelPages/myDashboard/Campaigns/CampaignBlock.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/ChooseCommunity.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/ExistingSpace.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/TryVC/TryVcInfo.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/TryVC/TryVirtualContributorDialog.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/TryVC/utils.ts
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/newVirtualContributorQueries.graphql
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/useVirtualContributorWizard.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/virtualContributorProps.ts
Labels: client

#7489 apply multiple filters on space activities
  src/main/topLevelPages/myDashboard/latestContributions/LatestContributions.tsx
Labels: bug, client

#7493 fix paste issue
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
Labels: bug, client

#7501 fix md editor typing issue
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
Labels: bug, client

#7521 subspace settings incorrect text
  src/core/i18n/en/translation.en.json
  src/domain/journey/space/pages/SpaceSettings/SpaceSettingsView.tsx
Labels: bug, client

#7569 bug fix - wrong text in subspace settings
  src/core/i18n/en/translation.en.json
Labels: bug, client

#7531 Retrieve the iframeAllowedUrls from the server
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/core/ui/forms/MarkdownInputControls/InsertEmbedCodeButton/InsertEmbedCodeButton.tsx
  src/core/ui/markdown/WrapperMarkdown.tsx
  src/core/ui/markdown/embed/allowedEmbedUrls.ts
  src/core/ui/markdown/embed/remarkVerifyIframe.ts
  src/domain/platform/config/ConfigProvider.tsx
  src/domain/platform/config/configuration.graphql
  src/domain/platform/config/configuration.ts
  src/domain/platform/config/useConfig.ts
Labels: client, enhancement
