Repository alkem-io/client-web, pull requests merged in 2025-02, with the labels that each got.

#7556 add vc references
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/domain/community/virtualContributor/VirtualContributor.graphql
  src/domain/community/virtualContributor/vcProfilePage/VCProfilePage.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfilePageView.tsx
  src/domain/community/virtualContributor/vcProfilePage/model.ts
  src/domain/community/virtualContributorAdmin/vcSettingsPage/VirtualContributorForm.tsx
  src/domain/platform/admin/components/Common/ReferenceSegment.tsx
Labels: client

#7565 VC store refinements (list page)
  src/core/i18n/en/translation.en.json
  src/core/ui/content/BlockTitleWithIcon.tsx
  src/core/ui/content/PageContentBlockHeader.tsx
  src/domain/community/inviteContributors/InviteVCsDialog.tsx
Labels: client

#7606 UserProvider Optimization
  src/domain/community/profile/views/ProfileView/UserProfileView.tsx
  src/domain/community/user/providers/UserProvider/UserProvider.tsx
  src/domain/community/user/userProfilePage/UserProfilePage.tsx
Labels: client, enhancement, optimization

#7646 #7545 - Fix MD input title
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
Labels: bug, client

#7650 7545 [bug fix] - Fix MD editor's invisible placeholder
  src/core/ui/forms/MarkdownInput/FormikMarkdownField.tsx
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
Labels: client, bug squash

#7659 Client/7571 bugfix md editor paste
  src/core/ui/forms/MarkdownInput/MarkdownInput.tsx
  src/core/ui/forms/MarkdownInputControls/MarkdownInputControls.tsx
Labels: client, bug squash

#7667 7622 - Fix duplicated VCs in the VC store dialog
  src/domain/community/inviteContributors/InviteVCsDialog.tsx
Labels: client, bug squash

#7679 7673 [bug fix] Hide `No tags available.` signs from vc/org/user profiles and bio block
  src/domain/community/profile/views/ProfileView/UserProfileView.tsx
  src/domain/journey/common/PageBanner/JourneyPageBannerCard/PageBannerCardWithVisual.tsx
  src/domain/shared/components/TagsComponent/TagsComponent.tsx
Labels: client, bug squash

#7675 7669 [bug fix] VC store search issue
  package-lock.json
  src/core/i18n/en/translation.en.json
  src/domain/access/AvailableContributors/useRoleSetAvailableContributors.ts
  src/domain/access/_removeMe/useInviteContributors.tsx
  src/domain/collaboration/post/graphql/usePost.tsx
  src/domain/collaboration/post/graphql/usePostSettings.ts
  src/domain/community/community/VirtualContributorsBlock/VirtualContributorsDialog.tsx
  src/domain/community/inviteContributors/InviteVCsDialog.tsx
Labels: client, bug squash, enhancement

#7686 7673 [bug fix] Hide titles on empty tags, links, keywords and skills
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/domain/community/contributor/organization/OrganizationPageContainer/OrganizationPageContainer.tsx
  src/domain/community/contributor/organization/context/OrganizationInfoFragment.graphql
  src/domain/community/profile/views/ProfileView/OrganizationProfileView.tsx
  src/domain/community/profile/views/ProfileView/UserProfileView.tsx
  src/domain/journey/common/PageBanner/JourneyPageBannerCard/PageBannerCardWithVisual.tsx
  src/domain/shared/components/References/References.tsx
  src/domain/shared/components/SocialLinks/SocialLinks.tsx
  src/domain/shared/components/TagsComponent/TagsComponent.tsx
Labels: client, bug squash

#7698 Sync package lock changes after the latest npm i on develop
  package-lock.json
Labels: client

#7719 6312 - Add missing reference description in VC profile
  src/domain/community/virtualContributorAdmin/vcSettingsPage/VirtualContributorForm.tsx
Labels: client, bug squash

#7753 7562 - Fix missing avatar in subspace contributors dialog
  src/domain/community/community/utils/useUserCardProps.ts
Labels: client, bug squash

#7736 7511 - Fix VC cards in invite vc dialog
  src/domain/community/inviteContributors/InviteContributorsList.tsx
  src/domain/community/user/userCard/UserCard.tsx
Labels: client, bug squash

#7747 6695 - Add avatar upload in vc creation form
  src/core/apollo/generated/apollo-hooks.ts
  src/core/apollo/generated/graphql-schema.ts
  src/core/i18n/en/translation.en.json
  src/core/ui/upload/FormikVisualUpload/FormikVisualUpload.tsx
  src/domain/community/user/userForm/UserForm.tsx
  src/domain/journey/space/pages/SpaceSettings/VirtualContributor.graphql
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/CreateNewVirtualContributor.tsx
  src/main/topLevelPages/myDashboard/newVirtualContributorWizard/useVirtualContributorWizard.tsx
Labels: client, enhancement, UX

#7723 7170 - VC Profile transparency
  src/core/i18n/en/translation.en.json
  src/domain/community/virtualContributor/vcProfilePage/SettingsMotionModeIcon.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfileContentView.tsx
  src/domain/community/virtualContributor/vcProfilePage/VCProfilePageView.tsx
  src/domain/community/virtualContributor/vcProfilePage/useTemporaryHardCodedVCProfilePageData.ts
Labels: client, enhancement, UX
